package org.bhargav.pansariwala.data.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(
    entities = [
        UserEntity::class,
        ProductEntity::class,
        OrderEntity::class,
        OrderItemEntity::class,
    ],
    version = 2,
    exportSchema = true,
)
@ConstructedBy(ShopDatabaseConstructor::class)
abstract class ShopDatabase : RoomDatabase() {
    abstract fun userDao(): UserDao
    abstract fun productDao(): ProductDao
    abstract fun orderDao(): OrderDao
}

// The actual implementation is generated by Room's KSP processor per target.
@Suppress("NO_ACTUAL_FOR_EXPECT", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object ShopDatabaseConstructor : RoomDatabaseConstructor<ShopDatabase> {
    override fun initialize(): ShopDatabase
}
